[project]
name = "2-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "roshita", email = "roshlogin@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.5.9",
    "ipykernel>=7.3.0",
    "langchain>=1.4.0",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.3",
    "langchain-google-genai>=4.4.0",
    "pymupdf>=1.28.2",
    "python-dotenv>=1.2.3",
    "sentence-transformers>=6.0.1",
]

[project.scripts]
2-rag = "2_rag:main"

[build-system]
requires = ["uv_build>=0.12.14,<0.13.0"]
build-backend = "uv_build"
